on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+-*"
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Verify commit exists in origin/main
      run: git branch --remote --contains | grep origin/main
    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
    - name: Build
      run: dotnet build --configuration Release /p:Version=${VERSION} src
    - name: Test
      run: dotnet test --configuration Release /p:Version=${VERSION} --no-build src
    - name: Pack
      run: dotnet pack --configuration Release /p:Version=${VERSION} --no-build --output . src/Plumbum
    - name: Publish to Github
      run: dotnet nuget push Plumbum.${VERSION}.nupkg --source --source https://nuget.pkg.github.com/ltippmann/index.json --api-key ${PRERELEASE_GITHUB_API_KEY}
      env:
        PRERELEASE_GITHUB_API_KEY: ${{ secrets.PRERELEASE_GITHUB_API_KEY }}